#!/usr/bin/env python
"""uagent.setup_cli

Interactive setup wizard for end users (installed via pip/wheel).

Purpose:
- Generate a `.env` file in the current working directory.
- Optionally generate shell helper scripts: `env.sh`, `env.ps1`, `env.bat`.

Notes:
- This wizard is intentionally standalone (does not rely on repo `samples/`).
- It only writes to the selected output files in the current directory.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .i18n import _, detect_lang, set_thread_lang
from uag_envsec.secret_core import DEFAULT_SEC_SUFFIX, encrypt_text, ensure_key_file

# Setup wizard follows detected UI language.
set_thread_lang(detect_lang())

HEADER_ENV = "\n".join(
    [
        "# .env for uag (generated by `uag_setup`)",
        "#",
        "# Notes:",
        "# - This file may contain secrets (API keys). Do NOT commit it to Git.",
        "# - You can re-run `uag_setup` anytime to regenerate.",
    ]
).rstrip("\n")

HEADER_SH = "\n".join(
    [
        "#!/usr/bin/env bash",
        "# Auto-generated by uag_setup",
        "# Do not edit this file directly. Re-run uag_setup to regenerate.",
    ]
).rstrip("\n")

HEADER_PS1 = "\n".join(
    [
        "<#",
        " Auto-generated by uag_setup",
        " Do not edit this file directly. Re-run uag_setup to regenerate.",
        "#>",
    ]
).rstrip("\n")

HEADER_BAT = "\n".join(
    [
        "@echo off",
        "REM Auto-generated by uag_setup",
        "REM Do not edit this file directly. Re-run uag_setup to regenerate.",
    ]
).rstrip("\n")

PROVIDERS: list[tuple[str, str]] = [
    ("openai", "OpenAI-compatible"),
    ("azure", "Azure OpenAI"),
    ("bedrock", "Bedrock OpenAI-compatible gateway"),
    ("openrouter", "OpenRouter"),
    ("gemini", "Gemini"),
    ("vertexai", "Vertex AI"),
    ("grok", "Grok"),
    ("claude", "Claude"),
    ("ollama", "Ollama"),
    ("nvidia", "NVIDIA"),
]

# key, required, label
PROVIDER_FIELDS: dict[str, list[tuple[str, bool, str]]] = {
    "openai": [
        ("UAGENT_OPENAI_API_KEY", True, _("OpenAI API key")),
        ("UAGENT_OPENAI_BASE_URL", False, _("OpenAI base URL (optional)")),
        ("UAGENT_OPENAI_DEPNAME", False, _("OpenAI model/deployment name (optional)")),
    ],
    "azure": [
        (
            "UAGENT_AZURE_BASE_URL",
            True,
            _("Azure base URL (e.g. https://<resource>.openai.azure.com/)"),
        ),
        ("UAGENT_AZURE_API_KEY", True, _("Azure API key")),
        (
            "UAGENT_AZURE_API_VERSION",
            False,
            _("Azure API version (optional, e.g. 2024-05-01-preview)"),
        ),
        ("UAGENT_AZURE_DEPNAME", True, _("Azure deployment name")),
    ],
    "bedrock": [
        (
            "UAGENT_BEDROCK_BASE_URL",
            True,
            _("Bedrock gateway base URL (e.g. https://<gateway>/v1)"),
        ),
        ("UAGENT_BEDROCK_API_KEY", True, _("Bedrock API key")),
        (
            "UAGENT_BEDROCK_DEPNAME",
            True,
            _("Bedrock model/deployment name (e.g. openai.gpt-oss-120b)"),
        ),
    ],
    "openrouter": [
        ("UAGENT_OPENROUTER_API_KEY", True, _("OpenRouter API key")),
        ("UAGENT_OPENROUTER_BASE_URL", False, _("OpenRouter base URL (optional)")),
        (
            "UAGENT_OPENROUTER_DEPNAME",
            False,
            _("OpenRouter model/deployment name (optional)"),
        ),
        (
            "UAGENT_OPENROUTER_FALLBACK_MODELS",
            False,
            _("OpenRouter fallback models (optional, comma-separated)"),
        ),
    ],
    "gemini": [
        ("UAGENT_GEMINI_API_KEY", True, _("Gemini API key")),
        ("UAGENT_GEMINI_DEPNAME", False, _("Gemini model name (optional)")),
    ],
    "vertexai": [
        ("UAGENT_VERTEXAI_API_KEY", True, _("Vertex AI API key")),
        ("UAGENT_VERTEXAI_PROJECT", False, _("Vertex AI project ID (optional)")),
        ("UAGENT_VERTEXAI_LOCATION", False, _("Vertex AI location/region (optional)")),
        ("UAGENT_VERTEXAI_DEPNAME", True, _("Vertex AI model/deployment name")),
    ],
    "grok": [
        ("UAGENT_GROK_API_KEY", True, _("Grok API key")),
        ("UAGENT_GROK_BASE_URL", False, _("Grok base URL (optional)")),
        ("UAGENT_GROK_DEPNAME", False, _("Grok model/deployment name (optional)")),
    ],
    "claude": [
        ("UAGENT_CLAUDE_API_KEY", True, _("Claude API key")),
        ("UAGENT_CLAUDE_DEPNAME", False, _("Claude model/deployment name (optional)")),
    ],
    "nvidia": [
        ("UAGENT_NVIDIA_API_KEY", True, _("NVIDIA API key")),
        ("UAGENT_NVIDIA_BASE_URL", False, _("NVIDIA base URL (optional)")),
        ("UAGENT_NVIDIA_DEPNAME", False, _("NVIDIA model/deployment name (optional)")),
    ],
    "ollama": [
        (
            "UAGENT_OLLAMA_BASE_URL",
            True,
            _("Ollama base URL (e.g. http://localhost:11434/v1)"),
        ),
        (
            "UAGENT_OLLAMA_API_KEY",
            False,
            _("Ollama API key (optional, default: dummy)"),
        ),
        ("UAGENT_OLLAMA_DEPNAME", False, _("Ollama model/deployment name (optional)")),
        (
            "UAGENT_OLLAMA_TIMEOUT_SEC",
            False,
            _("Ollama request timeout in seconds (default: 60)"),
        ),
        ("UAGENT_OLLAMA_TEMPERATURE", False, _("Ollama temperature (default: 0.7)")),
        ("UAGENT_OLLAMA_TOP_P", False, _("Ollama top_p (default: 0.9)")),
        ("UAGENT_OLLAMA_TOP_K", False, _("Ollama top_k (default: 40)")),
        (
            "UAGENT_OLLAMA_REPEAT_PENALTY",
            False,
            _("Ollama repeat_penalty (default: 1.1)"),
        ),
        ("UAGENT_OLLAMA_KEEP_ALIVE", False, _("Ollama keep_alive (default: 5m)")),
        ("UAGENT_OLLAMA_NUM_CTX", False, _("Ollama num_ctx (default: 8192)")),
        ("UAGENT_OLLAMA_NUM_PREDICT", False, _("Ollama num_predict (default: 1024)")),
    ],
}

RESPONSES_PROVIDERS = {"openai", "azure", "bedrock", "openrouter", "ollama"}

LANG_PRESETS = ["en", "ja", "zh_CN", "zh_TW", "ko", "th", "es", "fr", "sw"]

IMAGE_ANALYSIS_PROVIDERS: list[tuple[str, str]] = [
    ("openai", "OpenAI-compatible"),
    ("azure", "Azure OpenAI"),
    ("bedrock", "Bedrock OpenAI-compatible gateway"),
    ("openrouter", "OpenRouter"),
]

IMAGE_GENERATION_PROVIDERS: list[tuple[str, str]] = [
    ("azure", "Azure OpenAI"),
    ("openai", "OpenAI-compatible"),
    ("bedrock", "Bedrock OpenAI-compatible gateway"),
    ("openrouter", "OpenRouter"),
    ("gemini", "Gemini"),
    ("nvidia", "NVIDIA"),
]

AUDIO_PROVIDERS: list[tuple[str, str]] = [
    ("openai", "OpenAI-compatible"),
    ("azure", "Azure OpenAI"),
]


@dataclass
class _WizardState:
    provider: str = "openai"

    # Responses
    responses_enabled: bool = False
    reasoning: str = "medium"
    verbosity: str = "medium"

    # Optional runtime
    workdir_enabled: bool = False
    workdir: str = "."
    lang_enabled: bool = False
    lang: str = "ja"

    # Optional tools / extras
    extra_enabled: bool = False
    image_analysis_enabled: bool = False
    image_generate_enabled: bool = False
    embedding_enabled: bool = False
    audio_enabled: bool = False
    image_open_enabled: bool = True
    audio_open_enabled: bool = True

    # Provider-specific values
    values: dict[str, str] | None = None
    image_analysis_values: dict[str, str] | None = None
    image_generate_values: dict[str, str] | None = None
    embedding_values: dict[str, str] | None = None


def _q_sh(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def _q_ps1(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _split_kv(s: str) -> tuple[str, str]:
    key, value = s.split("=", 1)
    return key.strip(), value.strip()


def _emit_sh(lines: list[str]) -> str:
    out: list[str] = [HEADER_SH, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# export {k}={_q_sh(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"export {k}={_q_sh(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_ps1(lines: list[str]) -> str:
    out: list[str] = [HEADER_PS1, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# $env:{k} = {_q_ps1(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"$env:{k} = {_q_ps1(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_bat(lines: list[str]) -> str:
    out: list[str] = [HEADER_BAT, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"REM set {k}={v}")
            else:
                out.append(f"REM {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"set {k}={v}")
        else:
            out.append(f"REM {s}")
    return "\r\n".join(out).rstrip() + "\r\n"


def _menu_choice(
    title: str,
    options: list[str],
    default_index: int = 1,
    allow_back: bool = False,
) -> str:
    while True:
        print()
        print(title)
        for i, text in enumerate(options, 1):
            mark = " (default)" if i == default_index else ""
            print(f"  {i}. {text}{mark}")
        hint = _("Enter number:")
        if allow_back:
            hint += " b=back"
        hint += " q=quit"
        raw = input(f"{hint} ").strip().lower()
        if raw == "q":
            return "__quit__"
        if allow_back and raw == "b":
            return "__back__"
        if not raw:
            return str(default_index)
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return raw
        print(_("Invalid input. Please enter a valid number."))


def _ask_text(
    label: str,
    *,
    default: str = "",
    required: bool = False,
    allow_back: bool = True,
) -> tuple[str, str]:
    while True:
        prompt = label
        if default:
            prompt += _(" [default: %(default)s]") % {"default": default}
        hint: list[str] = []
        if allow_back:
            hint.append("b=back")
        hint.append("q=quit")
        prompt += f" ({', '.join(hint)}): "
        raw = input(prompt).strip()
        low = raw.lower()
        if low == "q":
            return "__quit__", ""
        if allow_back and low == "b":
            return "__back__", ""
        if not raw:
            if default:
                return "ok", default
            if required:
                print(_("This field is required. Please enter a value."))
                continue
            return "ok", ""
        return "ok", raw


def _ask_lang(default: str, allow_back: bool = True) -> tuple[str, str]:
    opts = [*LANG_PRESETS, "custom..."]
    default_index = 1
    if default in LANG_PRESETS:
        default_index = LANG_PRESETS.index(default) + 1
    choice = _menu_choice(
        _("Select UAGENT_LANG"),
        opts,
        default_index=default_index,
        allow_back=allow_back,
    )
    if choice in {"__quit__", "__back__"}:
        return choice, ""
    idx = int(choice) - 1
    if idx < len(LANG_PRESETS):
        return "ok", LANG_PRESETS[idx]
    status, val = _ask_text(
        _("UAGENT_LANG (custom)"),
        default=default,
        required=False,
        allow_back=allow_back,
    )
    if status in {"__quit__", "__back__"}:
        return status, ""
    return "ok", val


def _ask_outputs(allow_back: bool = True) -> tuple[str, set[str]]:
    # Returns selected kinds: {"env","sh","ps1","bat"}
    print()
    print(_("Select output files to generate in the current directory"))
    print(_("  1. .env only"))
    print("  2. .env + env.sh")
    print("  3. .env + env.ps1")
    print("  4. .env + env.bat")
    print(_("  5. .env + all (sh/ps1/bat)"))
    if allow_back:
        print("  b. back")
    print("  q. quit")

    while True:
        raw = input(_("Enter number:") + " ").strip().lower()
        if raw == "q":
            return "__quit__", set()
        if allow_back and raw == "b":
            return "__back__", set()
        if raw in {"1", "2", "3", "4", "5"}:
            if raw == "1":
                return "ok", {"env"}
            if raw == "2":
                return "ok", {"env", "sh"}
            if raw == "3":
                return "ok", {"env", "ps1"}
            if raw == "4":
                return "ok", {"env", "bat"}
            return "ok", {"env", "sh", "ps1", "bat"}
        print(_("Invalid input. Please enter 1-5, or b/q."))


def _clear_optional_extra_values(st: _WizardState) -> None:
    st.image_analysis_values = None
    st.image_generate_values = None
    st.embedding_values = None
    st.audio_values = None
    st.audio_enabled = False


def _ask_provider_image_values(
    provider: str,
    mode: str,
    *,
    allow_back: bool = True,
    current: dict[str, str] | None = None,
) -> tuple[str, dict[str, str]]:
    vals = dict(current or {})

    if provider == "azure":
        specs = [
            (
                "base_url",
                True,
                _("Azure base URL (e.g. https://<resource>.openai.azure.com/)"),
            ),
            ("api_key", True, _("Azure API key")),
            ("api_version", True, _("Azure API version (e.g. 2024-05-01-preview)")),
            ("depname", True, _("Azure deployment name")),
        ]
    elif provider == "openai":
        specs = [
            ("api_key", True, _("OpenAI API key")),
            ("base_url", False, _("OpenAI base URL (optional)")),
            ("depname", True, _("OpenAI model/deployment name")),
        ]
    elif provider == "bedrock":
        specs = [
            (
                "base_url",
                True,
                _("Bedrock gateway base URL (e.g. https://<gateway>/v1)"),
            ),
            ("api_key", True, _("Bedrock API key")),
            (
                "depname",
                True,
                _("Bedrock model/deployment name (e.g. openai.gpt-oss-120b)"),
            ),
        ]
    elif provider == "openrouter":
        specs = [
            ("api_key", True, _("OpenRouter API key")),
            ("base_url", False, _("OpenRouter base URL (optional)")),
            ("depname", True, _("OpenRouter model/deployment name")),
        ]
    elif provider == "gemini":
        specs = [
            ("api_key", True, _("Gemini API key")),
            ("depname", True, _("Gemini model name")),
        ]
    elif provider == "nvidia":
        specs = [
            ("api_key", True, _("NVIDIA API key")),
            ("base_url", False, _("NVIDIA base URL (optional)")),
            ("depname", True, _("NVIDIA model/deployment name")),
        ]
    else:
        return "ok", vals

    for suffix, required, label in specs:
        key = f"UAGENT_{provider.upper()}_IMG_{mode.upper()}_{suffix.upper()}"
        status, value = _ask_text(
            "%(label)s" % {"label": label},
            default=vals.get(key, ""),
            required=required,
            allow_back=allow_back,
        )
        if status in {"__quit__", "__back__"}:
            return status, vals
        vals[key] = value

    if mode == "generate":
        status, value = _ask_text(
            _("Enable image generation debug output? (0/1)"),
            default=vals.get("UAGENT_IMG_GENERATE_DEBUG", ""),
            required=False,
            allow_back=allow_back,
        )
        if status in {"__quit__", "__back__"}:
            return status, vals
        if value:
            vals["UAGENT_IMG_GENERATE_DEBUG"] = value

    return "ok", vals


def _ask_provider_audio_values(
    provider: str,
    *,
    allow_back: bool = True,
    current: dict[str, str] | None = None,
) -> tuple[str, dict[str, str]]:
    vals = dict(current or {})

    if provider == "azure":
        specs = [
            ("speech", True, _("Azure speech deployment name")),
            ("transcribe", True, _("Azure transcription deployment name")),
        ]
    elif provider == "openai":
        specs = [
            (
                "speech",
                False,
                _(
                    "OpenAI TTS model/deployment name (optional, default: gpt-4o-mini-tts)"
                ),
            ),
            (
                "transcribe",
                False,
                _(
                    "OpenAI transcription model/deployment name (optional, default: gpt-4o-mini-transcribe)"
                ),
            ),
        ]
        vals.setdefault("UAGENT_OPENAI_SPEECH_DEPNAME", "gpt-4o-mini-tts")
        vals.setdefault("UAGENT_OPENAI_TRANSCRIBE_DEPNAME", "gpt-4o-mini-transcribe")
    else:
        return "ok", vals

    for suffix, required, label in specs:
        key = f"UAGENT_{provider.upper()}_{suffix.upper()}_DEPNAME"
        status, value = _ask_text(
            "%(label)s" % {"label": label},
            default=vals.get(key, ""),
            required=required,
            allow_back=allow_back,
        )
        if status in {"__quit__", "__back__"}:
            return status, vals
        vals[key] = value

    return "ok", vals


def _ask_optional_extras(st: _WizardState) -> str:
    yn = _menu_choice(
        _("Configure optional image / embedding / audio settings?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=True,
    )
    if yn in {"__quit__", "__back__"}:
        return yn

    st.extra_enabled = yn == "2"
    _clear_optional_extra_values(st)
    if not st.extra_enabled:
        return "ok"

    # Image analysis
    ia = _menu_choice(
        _("Configure image analysis settings?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=True,
    )
    if ia in {"__quit__", "__back__"}:
        return ia
    st.image_analysis_enabled = ia == "2"
    if st.image_analysis_enabled:
        ia_options = [f"{prov} ({label})" for prov, label in IMAGE_ANALYSIS_PROVIDERS]
        ia_choice = _menu_choice(
            _("Select image analysis provider"),
            ia_options,
            default_index=1,
            allow_back=True,
        )
        if ia_choice in {"__quit__", "__back__"}:
            return ia_choice
        ia_provider = IMAGE_ANALYSIS_PROVIDERS[int(ia_choice) - 1][0]
        st.image_analysis_values = {"UAGENT_IMG_ANALYSIS_PROVIDER": ia_provider}
        status, vals = _ask_provider_image_values(
            ia_provider,
            "analysis",
            current=st.image_analysis_values,
            allow_back=True,
        )
        if status in {"__quit__", "__back__"}:
            return status
        st.image_analysis_values = vals

    # Image generation
    ig = _menu_choice(
        _("Configure image generation settings?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=True,
    )
    if ig in {"__quit__", "__back__"}:
        return ig
    st.image_generate_enabled = ig == "2"
    if st.image_generate_enabled:
        ig_options = [f"{prov} ({label})" for prov, label in IMAGE_GENERATION_PROVIDERS]
        ig_choice = _menu_choice(
            _("Select image generation provider"),
            ig_options,
            default_index=1,
            allow_back=True,
        )
        if ig_choice in {"__quit__", "__back__"}:
            return ig_choice
        ig_provider = IMAGE_GENERATION_PROVIDERS[int(ig_choice) - 1][0]
        st.image_generate_values = {"UAGENT_IMG_GENERATE_PROVIDER": ig_provider}
        status, vals = _ask_provider_image_values(
            ig_provider,
            "generate",
            current=st.image_generate_values,
            allow_back=True,
        )
        if status in {"__quit__", "__back__"}:
            return status
        st.image_generate_values = vals

        image_open = _menu_choice(
            _("Open generated images automatically?"),
            [_("No"), _("Yes")],
            default_index=2,
            allow_back=True,
        )
        if image_open in {"__quit__", "__back__"}:
            return image_open
        st.image_open_enabled = image_open == "2"
        if st.image_generate_values is None:
            st.image_generate_values = {}
        st.image_generate_values["UAGENT_IMAGE_OPEN"] = (
            "1" if st.image_open_enabled else "0"
        )

    # Embedding / semantic search
    emb = _menu_choice(
        _("Configure embedding / semantic search settings?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=True,
    )
    if emb in {"__quit__", "__back__"}:
        return emb
    st.embedding_enabled = emb == "2"
    if st.embedding_enabled:
        st.embedding_values = {}
        status, value = _ask_text(
            "UAGENT_EMBEDDING_API_URL",
            default="",
            required=True,
            allow_back=True,
        )
        if status in {"__quit__", "__back__"}:
            return status
        st.embedding_values["UAGENT_EMBEDDING_API_URL"] = value

        status, value = _ask_text(
            "UAGENT_EMBEDDING_API_HEALTHCHECK_PATH",
            default="/v1/models",
            required=False,
            allow_back=True,
        )
        if status in {"__quit__", "__back__"}:
            return status
        if value:
            st.embedding_values["UAGENT_EMBEDDING_API_HEALTHCHECK_PATH"] = value

        sem = _menu_choice(
            _("Disable semantic search when embedding API is unreachable?"),
            [_("No"), _("Yes")],
            default_index=2,
            allow_back=True,
        )
        if sem in {"__quit__", "__back__"}:
            return sem
        st.embedding_values["UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE"] = (
            "1" if sem == "2" else "0"
        )

    # Audio speech / transcription
    au = _menu_choice(
        _("Configure audio speech / transcription settings?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=True,
    )
    if au in {"__quit__", "__back__"}:
        return au
    st.audio_enabled = au == "2"
    if st.audio_enabled:
        au_options = [f"{prov} ({label})" for prov, label in AUDIO_PROVIDERS]
        au_default = 1
        if st.provider in {prov for prov, _ in AUDIO_PROVIDERS}:
            au_default = next(
                i + 1
                for i, (prov, _label) in enumerate(AUDIO_PROVIDERS)
                if prov == st.provider
            )
        au_choice = _menu_choice(
            _("Select audio provider"),
            au_options,
            default_index=au_default,
            allow_back=True,
        )
        if au_choice in {"__quit__", "__back__"}:
            return au_choice
        au_provider = AUDIO_PROVIDERS[int(au_choice) - 1][0]
        st.audio_values = {"UAGENT_AUDIO_PROVIDER": au_provider}
        status, vals = _ask_provider_audio_values(
            au_provider,
            current=st.audio_values,
            allow_back=True,
        )
        if status in {"__quit__", "__back__"}:
            return status
        st.audio_values = vals

        audio_open = _menu_choice(
            _("Open generated audio automatically?"),
            [_("No"), _("Yes")],
            default_index=2,
            allow_back=True,
        )
        if audio_open in {"__quit__", "__back__"}:
            return audio_open
        st.audio_open_enabled = audio_open == "2"
        if st.audio_values is None:
            st.audio_values = {}
        st.audio_values["UAGENT_AUDIO_OPEN"] = "1" if st.audio_open_enabled else "0"

    return "ok"


def _env_lines_from_state(st: _WizardState) -> list[str]:
    values: dict[str, str] = {}
    values["UAGENT_PROVIDER"] = st.provider

    if st.values:
        values.update(st.values)

    if st.responses_enabled:
        values["UAGENT_RESPONSES"] = "1"
        values["UAGENT_REASONING"] = st.reasoning
        values["UAGENT_VERBOSITY"] = st.verbosity

    if st.workdir_enabled and st.workdir.strip():
        values["UAGENT_WORKDIR"] = st.workdir.strip()

    if st.lang_enabled and st.lang.strip():
        values["UAGENT_LANG"] = st.lang.strip()

    out: list[str] = []
    out.extend(HEADER_ENV.splitlines())
    out.append("")

    out.append("# ==============================")
    out.append("# Provider selection")
    out.append("# ==============================")
    out.append(
        "# azure / openai / bedrock / openrouter / gemini / vertexai / grok / claude / ollama / nvidia"
    )
    out.append(f"UAGENT_PROVIDER={st.provider}")
    out.append("")

    def section(title: str) -> None:
        out.append("# ==============================")
        out.append(f"# {title}")
        out.append("# ==============================")

    for prov, label in PROVIDERS:
        section("%(label)s (UAGENT_PROVIDER=%(prov)s)" % {"label": label, "prov": prov})
        fields = PROVIDER_FIELDS[prov]
        for k, _req, _lab in fields:
            v = values.get(k, "") if prov == st.provider else ""
            if prov == st.provider:
                out.append(f"{k}={v}")
            else:
                out.append(f"# {k}=")
        out.append("")

    section(_("Optional: Responses API (Azure/OpenAI/Bedrock)"))
    if st.provider in RESPONSES_PROVIDERS:
        out.append("# UAGENT_RESPONSES=1")
        out.append("# UAGENT_REASONING=medium")
        out.append("# UAGENT_VERBOSITY=medium")
        if st.responses_enabled:
            out.append("UAGENT_RESPONSES=1")
            out.append(f"UAGENT_REASONING={st.reasoning}")
            out.append(f"UAGENT_VERBOSITY={st.verbosity}")
    else:
        out.append("# (not supported by selected provider)")
    out.append("")

    section(_("Optional runtime"))
    if st.workdir_enabled:
        out.append(f"UAGENT_WORKDIR={st.workdir.strip()}")
    else:
        out.append("# UAGENT_WORKDIR=.")

    if st.lang_enabled:
        out.append(f"UAGENT_LANG={st.lang.strip()}")
    else:
        out.append("# UAGENT_LANG=ja")
    out.append("")

    section(_("Optional image / embedding / audio settings"))
    if st.extra_enabled:
        if st.image_analysis_enabled:
            ia_vals = st.image_analysis_values or {}
            ia_provider = ia_vals.get("UAGENT_IMG_ANALYSIS_PROVIDER", "").strip()
            if ia_provider:
                out.append(f"UAGENT_IMG_ANALYSIS_PROVIDER={ia_provider}")
                for suffix in ("BASE_URL", "API_KEY", "API_VERSION", "DEPNAME"):
                    key = f"UAGENT_{ia_provider.upper()}_IMG_ANALYSIS_{suffix}"
                    val = ia_vals.get(key, "").strip()
                    if val:
                        out.append(f"{key}={val}")
        else:
            out.append("# UAGENT_IMG_ANALYSIS_PROVIDER=")
            for prov, _label in IMAGE_ANALYSIS_PROVIDERS:
                out.append(f"# UAGENT_{prov.upper()}_IMG_ANALYSIS_BASE_URL=")
                out.append(f"# UAGENT_{prov.upper()}_IMG_ANALYSIS_API_KEY=")
                if prov == "azure":
                    out.append(f"# UAGENT_{prov.upper()}_IMG_ANALYSIS_API_VERSION=")
                out.append(f"# UAGENT_{prov.upper()}_IMG_ANALYSIS_DEPNAME=")
        out.append("")

        if st.image_generate_enabled:
            ig_vals = st.image_generate_values or {}
            ig_provider = ig_vals.get("UAGENT_IMG_GENERATE_PROVIDER", "").strip()
            emitted: set[str] = {"UAGENT_IMG_GENERATE_PROVIDER"}
            if ig_provider:
                out.append(f"UAGENT_IMG_GENERATE_PROVIDER={ig_provider}")
                for suffix in ("BASE_URL", "API_KEY", "API_VERSION", "DEPNAME"):
                    key = f"UAGENT_{ig_provider.upper()}_IMG_GENERATE_{suffix}"
                    emitted.add(key)
                    val = ig_vals.get(key, "").strip()
                    if val:
                        out.append(f"{key}={val}")
            for key in sorted(ig_vals):
                if key in emitted:
                    continue
                val = (ig_vals.get(key, "") or "").strip()
                if val:
                    out.append(f"{key}={val}")
        else:
            out.append("# UAGENT_IMG_GENERATE_PROVIDER=")
            for prov, _label in IMAGE_GENERATION_PROVIDERS:
                out.append(f"# UAGENT_{prov.upper()}_IMG_GENERATE_BASE_URL=")
                out.append(f"# UAGENT_{prov.upper()}_IMG_GENERATE_API_KEY=")
                if prov == "azure":
                    out.append(f"# UAGENT_{prov.upper()}_IMG_GENERATE_API_VERSION=")
                out.append(f"# UAGENT_{prov.upper()}_IMG_GENERATE_DEPNAME=")
            out.append("# UAGENT_IMG_GENERATE_DEBUG=0")
            out.append("# UAGENT_IMAGE_OPEN=1")
        out.append("")

        if st.embedding_enabled:
            emb_vals = st.embedding_values or {}
            emb_url = emb_vals.get("UAGENT_EMBEDDING_API_URL", "").strip()
            if emb_url:
                out.append(f"UAGENT_EMBEDDING_API_URL={emb_url}")
            hc = emb_vals.get("UAGENT_EMBEDDING_API_HEALTHCHECK_PATH", "").strip()
            if hc:
                out.append(f"UAGENT_EMBEDDING_API_HEALTHCHECK_PATH={hc}")
            sem = emb_vals.get(
                "UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE", ""
            ).strip()
            if sem:
                out.append(f"UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE={sem}")
        else:
            out.append("# UAGENT_EMBEDDING_API_URL=")
            out.append("# UAGENT_EMBEDDING_API_HEALTHCHECK_PATH=/v1/models")
            out.append("# UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE=1")
        out.append("")

        if st.audio_enabled:
            audio_vals = st.audio_values or {}
            audio_provider = audio_vals.get("UAGENT_AUDIO_PROVIDER", "").strip()
            if audio_provider:
                out.append(f"UAGENT_AUDIO_PROVIDER={audio_provider}")
                if audio_provider == "azure":
                    for key in (
                        "UAGENT_AZURE_SPEECH_DEPNAME",
                        "UAGENT_AZURE_TRANSCRIBE_DEPNAME",
                    ):
                        val = audio_vals.get(key, "").strip()
                        if val:
                            out.append(f"{key}={val}")
                elif audio_provider == "openai":
                    for key in (
                        "UAGENT_OPENAI_SPEECH_DEPNAME",
                        "UAGENT_OPENAI_TRANSCRIBE_DEPNAME",
                    ):
                        val = audio_vals.get(key, "").strip()
                        if val:
                            out.append(f"{key}={val}")
            audio_open = audio_vals.get("UAGENT_AUDIO_OPEN", "").strip()
            if audio_open:
                out.append(f"UAGENT_AUDIO_OPEN={audio_open}")
        else:
            out.append("# UAGENT_AUDIO_PROVIDER=")
            out.append("# UAGENT_AZURE_SPEECH_DEPNAME=")
            out.append("# UAGENT_OPENAI_SPEECH_DEPNAME=")
            out.append("# UAGENT_AZURE_TRANSCRIBE_DEPNAME=")
            out.append("# UAGENT_OPENAI_TRANSCRIBE_DEPNAME=")
            out.append("# UAGENT_AUDIO_OPEN=1")
        out.append("")
    else:
        out.append("# (optional image / embedding settings not configured)")
        out.append("")

    return out


def _ask_encrypt_env() -> tuple[bool, str]:
    yn = _menu_choice(
        _("Encrypt the generated .env file?"),
        [_("No"), _("Yes")],
        default_index=1,
        allow_back=False,
    )
    if yn == "2":
        return True, _("Encrypted file will be written as %(path)s")
    return False, ""


def main() -> int:
    st = _WizardState(values={})

    stage = 0
    provider_fields: list[tuple[str, bool, str]] = []
    field_index = 0
    outputs: set[str] = {"env"}

    while True:
        if stage == 0:
            options = [f"{p} ({label})" for p, label in PROVIDERS]
            choice = _menu_choice(
                _("Select provider"), options, default_index=2, allow_back=False
            )
            if choice == "__quit__":
                print(_("Cancelled."))
                return 1
            st.provider = PROVIDERS[int(choice) - 1][0]
            provider_fields = PROVIDER_FIELDS[st.provider]
            field_index = 0
            stage = 1
            continue

        if stage == 1:
            if field_index >= len(provider_fields):
                stage = 2
                continue

            key, required, label = provider_fields[field_index]
            default = (st.values or {}).get(key, "")
            status, value = _ask_text(
                label, default=default, required=required, allow_back=True
            )
            if status == "__quit__":
                print(_("Cancelled."))
                return 1
            if status == "__back__":
                if field_index == 0:
                    stage = 0
                else:
                    field_index -= 1
                continue
            if st.values is None:
                st.values = {}
            st.values[key] = value
            field_index += 1
            continue

        if stage == 2:
            if st.provider in RESPONSES_PROVIDERS:
                yn = _menu_choice(
                    _("Enable Responses API options?"),
                    [_("No"), _("Yes")],
                    default_index=2,
                    allow_back=True,
                )
                if yn == "__quit__":
                    print(_("Cancelled."))
                    return 1
                if yn == "__back__":
                    stage = 1
                    field_index = max(0, len(provider_fields) - 1)
                    continue
                st.responses_enabled = yn == "2"

                if st.responses_enabled:
                    r = _menu_choice(
                        _("Select reasoning"),
                        ["minimal", "low", "medium", "high", "auto"],
                        default_index=3,
                        allow_back=True,
                    )
                    if r == "__quit__":
                        print(_("Cancelled."))
                        return 1
                    if r == "__back__":
                        continue
                    st.reasoning = [
                        "minimal",
                        "low",
                        "medium",
                        "high",
                        "auto",
                    ][int(r) - 1]

                    v = _menu_choice(
                        _("Select verbosity"),
                        ["low", "medium", "high"],
                        default_index=2,
                        allow_back=True,
                    )
                    if v == "__quit__":
                        print(_("Cancelled."))
                        return 1
                    if v == "__back__":
                        continue
                    st.verbosity = ["low", "medium", "high"][int(v) - 1]
            else:
                st.responses_enabled = False

            stage = 3
            continue

        if stage == 3:
            w = _menu_choice(
                _("Set optional runtime UAGENT_WORKDIR?"),
                [_("No"), _("Yes")],
                default_index=1,
                allow_back=True,
            )
            if w == "__quit__":
                print(_("Cancelled."))
                return 1
            if w == "__back__":
                stage = 2
                continue
            st.workdir_enabled = w == "2"
            if st.workdir_enabled:
                status, value = _ask_text(
                    "UAGENT_WORKDIR",
                    default=st.workdir,
                    required=False,
                    allow_back=True,
                )
                if status == "__quit__":
                    print(_("Cancelled."))
                    return 1
                if status == "__back__":
                    continue
                st.workdir = value

            lang_choice = _menu_choice(
                _("Set optional runtime UAGENT_LANG?"),
                [_("No"), _("Yes")],
                default_index=1,
                allow_back=True,
            )
            if lang_choice == "__quit__":
                print(_("Cancelled."))
                return 1
            if lang_choice == "__back__":
                continue
            st.lang_enabled = lang_choice == "2"
            if st.lang_enabled:
                status, value = _ask_lang(st.lang, allow_back=True)
                if status == "__quit__":
                    print(_("Cancelled."))
                    return 1
                if status == "__back__":
                    continue
                st.lang = value

            stage = 4
            continue

        if stage == 4:
            status = _ask_optional_extras(st)
            if status == "__quit__":
                print(_("Cancelled."))
                return 1
            if status == "__back__":
                stage = 3
                continue
            stage = 5
            continue

        if stage == 5:
            status, out_sel = _ask_outputs(allow_back=True)
            if status == "__quit__":
                print(_("Cancelled."))
                return 1
            if status == "__back__":
                stage = 4
                continue
            outputs = out_sel

            stage = 6
            continue

        if stage == 6:
            print()
            print(_("Summary"))
            print(_("  Provider: %(provider)s") % {"provider": st.provider})
            for key, req, label in PROVIDER_FIELDS[st.provider]:
                print(
                    "  %(key)s=%(value)s"
                    % {"key": key, "value": (st.values or {}).get(key, "")}
                )
            print(
                _("  Responses enabled: %(state)s")
                % {"state": _("yes") if st.responses_enabled else _("no")}
            )
            if st.responses_enabled:
                print("  UAGENT_REASONING=%(value)s" % {"value": st.reasoning})
                print("  UAGENT_VERBOSITY=%(value)s" % {"value": st.verbosity})
            print(
                "  UAGENT_WORKDIR enabled: %(state)s"
                % {"state": _("yes") if st.workdir_enabled else _("no")}
            )
            if st.workdir_enabled:
                print("  UAGENT_WORKDIR=%(value)s" % {"value": st.workdir})
            print(
                "  UAGENT_LANG enabled: %(state)s"
                % {"state": _("yes") if st.lang_enabled else _("no")}
            )
            if st.lang_enabled:
                print("  UAGENT_LANG=%(value)s" % {"value": st.lang})
            print(
                _("  Optional extras enabled: %(state)s")
                % {"state": _("yes") if st.extra_enabled else _("no")}
            )
            if st.extra_enabled:
                print(
                    _("  Image analysis enabled: %(state)s")
                    % {"state": _("yes") if st.image_analysis_enabled else _("no")}
                )
                if st.image_analysis_enabled:
                    print(
                        f"  UAGENT_IMG_ANALYSIS_PROVIDER={(st.values or {}).get('UAGENT_IMG_ANALYSIS_PROVIDER', '')}"
                    )
                print(
                    _("  Image generation enabled: %(state)s")
                    % {"state": _("yes") if st.image_generate_enabled else _("no")}
                )
                if st.image_generate_enabled:
                    print(
                        f"  UAGENT_IMG_GENERATE_PROVIDER={(st.values or {}).get('UAGENT_IMG_GENERATE_PROVIDER', '')}"
                    )
                    print(
                        f"  UAGENT_IMAGE_OPEN={(st.values or {}).get('UAGENT_IMAGE_OPEN', '')}"
                    )
                print(
                    _("  Embedding enabled: %(state)s")
                    % {"state": _("yes") if st.embedding_enabled else _("no")}
                )
                if st.embedding_enabled:
                    print(
                        f"  UAGENT_EMBEDDING_API_URL={(st.values or {}).get('UAGENT_EMBEDDING_API_URL', '')}"
                    )
                    print(
                        f"  UAGENT_EMBEDDING_API_HEALTHCHECK_PATH={(st.values or {}).get('UAGENT_EMBEDDING_API_HEALTHCHECK_PATH', '')}"
                    )
                    print(
                        f"  UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE={(st.values or {}).get('UAGENT_SEMANTIC_SEARCH_DISABLE_IF_UNREACHABLE', '')}"
                    )
            print(_("  Outputs: %(outputs)s") % {"outputs": ", ".join(sorted(outputs))})

            action = _menu_choice(
                _("Generate files with this configuration?"),
                [_("Yes, generate"), _("Back")],
                default_index=2,
                allow_back=False,
            )
            if action == "__quit__":
                print(_("Cancelled."))
                return 1
            if action == "2":
                stage = 5
                continue
            break

    out_dir = Path.cwd().resolve()
    paths: dict[str, Path] = {
        "env": out_dir / ".env",
        "sh": out_dir / "env.sh",
        "ps1": out_dir / "env.ps1",
        "bat": out_dir / "env.bat",
    }

    targets = [paths[k] for k in ("env", "sh", "ps1", "bat") if k in outputs]
    existing = [p for p in targets if p.exists()]
    if existing:
        print()
        print(_("The following files already exist and will be overwritten:"))
        for p in existing:
            print(f"  - {p}")
        yn = _menu_choice(
            _("Proceed?"), [_("No"), _("Yes")], default_index=2, allow_back=False
        )
        if yn == "__quit__" or yn == "1":
            print(_("Cancelled."))
            return 1

    env_lines = _env_lines_from_state(st)

    if "env" in outputs:
        env_text = "\n".join(env_lines).rstrip() + "\n"
        paths["env"].write_text(env_text, encoding="utf-8", newline="\n")

        encrypt_choice, encrypt_msg = _ask_encrypt_env()
        if encrypt_choice:
            ensure_key_file()
            sec_path = paths["env"].with_suffix(
                paths["env"].suffix + DEFAULT_SEC_SUFFIX
            )
            sec_text = encrypt_text(env_text)
            sec_path.write_text(sec_text + "\n", encoding="utf-8", newline="\n")
            print(encrypt_msg % {"path": sec_path})
            # Remove plain .env after encryption
            try:
                paths["env"].unlink()
                print(_("Plain .env file removed after encryption."))
            except Exception as e:
                print(
                    _("Warning: Failed to remove plain .env: %(error)s") % {"error": e}
                )

    if "sh" in outputs:
        sh_text = _emit_sh(env_lines)
        paths["sh"].write_text(sh_text, encoding="utf-8", newline="\n")

    if "ps1" in outputs:
        ps1_text = _emit_ps1(env_lines).replace("\n", "\r\n")
        # newline="" means: do not translate; we already have CRLF.
        paths["ps1"].write_text(ps1_text, encoding="utf-8-sig", newline="")

    if "bat" in outputs:
        bat_text = _emit_bat(env_lines)
        paths["bat"].write_text(bat_text, encoding="cp932", newline="")

    print()
    for k in ("env", "sh", "ps1", "bat"):
        if k in outputs:
            print(_("generated: %(path)s") % {"path": paths[k]})

    if "ps1" in outputs:
        print("- env.ps1 : utf-8-sig, CRLF")
    if "bat" in outputs:
        print("- env.bat : cp932, CRLF")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
