#!/usr/bin/env python
"""uagent.setup_cli

Interactive setup wizard for end users (installed via pip/wheel).

Purpose:
- Generate a `.env` file in the current working directory.
- Optionally generate shell helper scripts: `env.sh`, `env.ps1`, `env.bat`.

Notes:
- This wizard is intentionally standalone (does not rely on repo `samples/`).
- It only writes to the selected output files in the current directory.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


HEADER_ENV = """# .env for uag (generated by `uag_setup`)
#
# Notes:
# - This file may contain secrets (API keys). Do NOT commit it to Git.
# - You can re-run `uag_setup` anytime to regenerate.
""".rstrip("\n")

HEADER_SH = """#!/usr/bin/env bash
# Auto-generated by uag_setup
# Do not edit this file directly. Re-run uag_setup to regenerate.
""".rstrip("\n")

HEADER_PS1 = """<#
 Auto-generated by uag_setup
 Do not edit this file directly. Re-run uag_setup to regenerate.
#>
""".rstrip("\n")

HEADER_BAT = """@echo off
REM Auto-generated by uag_setup
REM Do not edit this file directly. Re-run uag_setup to regenerate.
""".rstrip("\n")


PROVIDERS: list[tuple[str, str]] = [
    ("openai", "OpenAI-compatible"),
    ("azure", "Azure OpenAI"),
    ("bedrock", "Bedrock OpenAI-compatible gateway"),
    ("openrouter", "OpenRouter"),
    ("gemini", "Gemini"),
    ("grok", "Grok"),
    ("claude", "Claude"),
    ("nvidia", "NVIDIA"),
]

# key, required, label
PROVIDER_FIELDS: dict[str, list[tuple[str, bool, str]]] = {
    "openai": [
        ("UAGENT_OPENAI_API_KEY", True, "OpenAI API key"),
        ("UAGENT_OPENAI_BASE_URL", False, "OpenAI base URL (optional)"),
        ("UAGENT_OPENAI_DEPNAME", False, "OpenAI model/deployment name (optional)"),
    ],
    "azure": [
        ("UAGENT_AZURE_BASE_URL", True, "Azure base URL (e.g. https://<resource>.openai.azure.com/)"),
        ("UAGENT_AZURE_API_KEY", True, "Azure API key"),
        ("UAGENT_AZURE_API_VERSION", False, "Azure API version (optional, e.g. 2024-05-01-preview)"),
        ("UAGENT_AZURE_DEPNAME", True, "Azure deployment name"),
    ],
    "bedrock": [
        ("UAGENT_BEDROCK_BASE_URL", True, "Bedrock gateway base URL (e.g. https://<gateway>/v1)"),
        ("UAGENT_BEDROCK_API_KEY", True, "Bedrock API key"),
        ("UAGENT_BEDROCK_DEPNAME", True, "Bedrock model/deployment name (e.g. openai.gpt-oss-120b)"),
    ],
    "openrouter": [
        ("UAGENT_OPENROUTER_API_KEY", True, "OpenRouter API key"),
        ("UAGENT_OPENROUTER_BASE_URL", False, "OpenRouter base URL (optional)"),
        ("UAGENT_OPENROUTER_DEPNAME", False, "OpenRouter model/deployment name (optional)"),
        (
            "UAGENT_OPENROUTER_FALLBACK_MODELS",
            False,
            "OpenRouter fallback models (optional, comma-separated)",
        ),
    ],
    "gemini": [
        ("UAGENT_GEMINI_API_KEY", True, "Gemini API key"),
        ("UAGENT_GEMINI_DEPNAME", False, "Gemini model name (optional)"),
    ],
    "grok": [
        ("UAGENT_GROK_API_KEY", True, "Grok API key"),
        ("UAGENT_GROK_BASE_URL", False, "Grok base URL (optional)"),
        ("UAGENT_GROK_DEPNAME", False, "Grok model/deployment name (optional)"),
    ],
    "claude": [
        ("UAGENT_CLAUDE_API_KEY", True, "Claude API key"),
        ("UAGENT_CLAUDE_DEPNAME", False, "Claude model/deployment name (optional)"),
    ],
    "nvidia": [
        ("UAGENT_NVIDIA_API_KEY", True, "NVIDIA API key"),
        ("UAGENT_NVIDIA_BASE_URL", False, "NVIDIA base URL (optional)"),
        ("UAGENT_NVIDIA_DEPNAME", False, "NVIDIA model/deployment name (optional)"),
    ],
}

RESPONSES_PROVIDERS = {"openai", "azure", "bedrock"}

LANG_PRESETS = [
    "en",
    "ja",
    "zh_CN",
    "zh_TW",
    "ko",
    "th",
    "es",
    "fr",
]


@dataclass
class _WizardState:
    provider: str = "openai"

    # Responses
    responses_enabled: bool = False
    reasoning: str = "medium"
    verbosity: str = "medium"

    # Optional runtime
    workdir_enabled: bool = False
    workdir: str = "."
    lang_enabled: bool = False
    lang: str = "ja"

    # Provider-specific values
    values: dict[str, str] | None = None


def _q_sh(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def _q_ps1(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _split_kv(s: str) -> tuple[str, str]:
    key, value = s.split("=", 1)
    return key.strip(), value.strip()


def _emit_sh(lines: list[str]) -> str:
    out: list[str] = [HEADER_SH, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# export {k}={_q_sh(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"export {k}={_q_sh(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_ps1(lines: list[str]) -> str:
    out: list[str] = [HEADER_PS1, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# $env:{k} = {_q_ps1(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"$env:{k} = {_q_ps1(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_bat(lines: list[str]) -> str:
    out: list[str] = [HEADER_BAT, ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"REM set {k}={v}")
            else:
                out.append(f"REM {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"set {k}={v}")
        else:
            out.append(f"REM {s}")
    return "\r\n".join(out).rstrip() + "\r\n"


def _menu_choice(
    title: str,
    options: list[str],
    default_index: int = 1,
    allow_back: bool = False,
) -> str:
    while True:
        print()
        print(title)
        for i, text in enumerate(options, 1):
            mark = " (default)" if i == default_index else ""
            print(f"  {i}. {text}{mark}")
        hint = "Enter number"
        if allow_back:
            hint += ", b=back"
        hint += ", q=quit"
        raw = input(f"{hint}: ").strip().lower()
        if raw == "q":
            return "__quit__"
        if allow_back and raw == "b":
            return "__back__"
        if not raw:
            return str(default_index)
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return raw
        print("Invalid input. Please enter a valid number.")


def _ask_text(
    label: str,
    *,
    default: str = "",
    required: bool = False,
    allow_back: bool = True,
) -> tuple[str, str]:
    while True:
        prompt = label
        if default:
            prompt += f" [default: {default}]"
        hint: list[str] = []
        if allow_back:
            hint.append("b=back")
        hint.append("q=quit")
        prompt += f" ({', '.join(hint)}): "
        raw = input(prompt).strip()
        low = raw.lower()
        if low == "q":
            return "__quit__", ""
        if allow_back and low == "b":
            return "__back__", ""
        if not raw:
            if default:
                return "ok", default
            if required:
                print("This field is required. Please enter a value.")
                continue
            return "ok", ""
        return "ok", raw


def _ask_lang(default: str, allow_back: bool = True) -> tuple[str, str]:
    opts = [*LANG_PRESETS, "custom..."]
    default_index = 1
    if default in LANG_PRESETS:
        default_index = LANG_PRESETS.index(default) + 1
    choice = _menu_choice(
        "Select UAGENT_LANG",
        opts,
        default_index=default_index,
        allow_back=allow_back,
    )
    if choice in {"__quit__", "__back__"}:
        return choice, ""
    idx = int(choice) - 1
    if idx < len(LANG_PRESETS):
        return "ok", LANG_PRESETS[idx]
    status, val = _ask_text(
        "UAGENT_LANG (custom)",
        default=default,
        required=False,
        allow_back=allow_back,
    )
    if status in {"__quit__", "__back__"}:
        return status, ""
    return "ok", val


def _ask_outputs(allow_back: bool = True) -> tuple[str, set[str]]:
    # Returns selected kinds: {"env","sh","ps1","bat"}
    print()
    print("Select output files to generate in the current directory")
    print("  1. .env only")
    print("  2. .env + env.sh")
    print("  3. .env + env.ps1")
    print("  4. .env + env.bat")
    print("  5. .env + all (sh/ps1/bat)")
    if allow_back:
        print("  b. back")
    print("  q. quit")

    while True:
        raw = input("Choice: ").strip().lower()
        if raw == "q":
            return "__quit__", set()
        if allow_back and raw == "b":
            return "__back__", set()
        if raw in {"1", "2", "3", "4", "5"}:
            if raw == "1":
                return "ok", {"env"}
            if raw == "2":
                return "ok", {"env", "sh"}
            if raw == "3":
                return "ok", {"env", "ps1"}
            if raw == "4":
                return "ok", {"env", "bat"}
            return "ok", {"env", "sh", "ps1", "bat"}
        print("Invalid input. Please enter 1-5, or b/q.")


def _env_lines_from_state(st: _WizardState) -> list[str]:
    values: dict[str, str] = {}
    values["UAGENT_PROVIDER"] = st.provider

    if st.values:
        values.update(st.values)

    if st.responses_enabled:
        values["UAGENT_RESPONSES"] = "1"
        values["UAGENT_REASONING"] = st.reasoning
        values["UAGENT_VERBOSITY"] = st.verbosity

    if st.workdir_enabled and st.workdir.strip():
        values["UAGENT_WORKDIR"] = st.workdir.strip()

    if st.lang_enabled and st.lang.strip():
        values["UAGENT_LANG"] = st.lang.strip()

    out: list[str] = []
    out.extend(HEADER_ENV.splitlines())
    out.append("")

    out.append("# ==============================")
    out.append("# Provider selection")
    out.append("# ==============================")
    out.append("# azure / openai / bedrock / openrouter / gemini / grok / claude / nvidia")
    out.append(f"UAGENT_PROVIDER={st.provider}")
    out.append("")

    def section(title: str) -> None:
        out.append("# ==============================")
        out.append(f"# {title}")
        out.append("# ==============================")

    for prov, label in PROVIDERS:
        section(f"{label} (UAGENT_PROVIDER={prov})")
        fields = PROVIDER_FIELDS[prov]
        for k, _req, _lab in fields:
            v = values.get(k, "") if prov == st.provider else ""
            if prov == st.provider:
                out.append(f"{k}={v}")
            else:
                out.append(f"# {k}=")
        out.append("")

    section("Optional: Responses API (Azure/OpenAI/Bedrock)")
    if st.provider in RESPONSES_PROVIDERS:
        out.append("# UAGENT_RESPONSES=1")
        out.append("# UAGENT_REASONING=medium")
        out.append("# UAGENT_VERBOSITY=medium")
        if st.responses_enabled:
            out.append("UAGENT_RESPONSES=1")
            out.append(f"UAGENT_REASONING={st.reasoning}")
            out.append(f"UAGENT_VERBOSITY={st.verbosity}")
    else:
        out.append("# (not supported by selected provider)")
    out.append("")

    section("Optional runtime")
    if st.workdir_enabled:
        out.append(f"UAGENT_WORKDIR={st.workdir.strip()}")
    else:
        out.append("# UAGENT_WORKDIR=.")

    if st.lang_enabled:
        out.append(f"UAGENT_LANG={st.lang.strip()}")
    else:
        out.append("# UAGENT_LANG=ja")

    out.append("")
    return out


def main() -> int:
    st = _WizardState(values={})

    stage = 0
    provider_fields: list[tuple[str, bool, str]] = []
    field_index = 0
    outputs: set[str] = {"env"}

    while True:
        if stage == 0:
            options = [f"{p} ({label})" for p, label in PROVIDERS]
            choice = _menu_choice("Select provider", options, default_index=1, allow_back=False)
            if choice == "__quit__":
                print("Cancelled.")
                return 1
            st.provider = PROVIDERS[int(choice) - 1][0]
            provider_fields = PROVIDER_FIELDS[st.provider]
            field_index = 0
            stage = 1
            continue

        if stage == 1:
            if field_index >= len(provider_fields):
                stage = 2
                continue

            key, required, label = provider_fields[field_index]
            default = (st.values or {}).get(key, "")
            status, value = _ask_text(label, default=default, required=required, allow_back=True)
            if status == "__quit__":
                print("Cancelled.")
                return 1
            if status == "__back__":
                if field_index == 0:
                    stage = 0
                else:
                    field_index -= 1
                continue
            if st.values is None:
                st.values = {}
            st.values[key] = value
            field_index += 1
            continue

        if stage == 2:
            if st.provider in RESPONSES_PROVIDERS:
                yn = _menu_choice(
                    "Enable Responses API options?",
                    ["No", "Yes"],
                    default_index=1,
                    allow_back=True,
                )
                if yn == "__quit__":
                    print("Cancelled.")
                    return 1
                if yn == "__back__":
                    stage = 1
                    field_index = max(0, len(provider_fields) - 1)
                    continue
                st.responses_enabled = yn == "2"

                if st.responses_enabled:
                    r = _menu_choice(
                        "Select reasoning",
                        ["minimal", "low", "medium", "high", "auto"],
                        default_index=3,
                        allow_back=True,
                    )
                    if r == "__quit__":
                        print("Cancelled.")
                        return 1
                    if r == "__back__":
                        continue
                    st.reasoning = ["minimal", "low", "medium", "high", "auto"][int(r) - 1]

                    v = _menu_choice(
                        "Select verbosity",
                        ["low", "medium", "high"],
                        default_index=2,
                        allow_back=True,
                    )
                    if v == "__quit__":
                        print("Cancelled.")
                        return 1
                    if v == "__back__":
                        continue
                    st.verbosity = ["low", "medium", "high"][int(v) - 1]
            else:
                st.responses_enabled = False

            stage = 3
            continue

        if stage == 3:
            w = _menu_choice(
                "Set optional runtime UAGENT_WORKDIR?",
                ["No", "Yes"],
                default_index=1,
                allow_back=True,
            )
            if w == "__quit__":
                print("Cancelled.")
                return 1
            if w == "__back__":
                stage = 2
                continue
            st.workdir_enabled = w == "2"
            if st.workdir_enabled:
                status, value = _ask_text("UAGENT_WORKDIR", default=st.workdir, required=False, allow_back=True)
                if status == "__quit__":
                    print("Cancelled.")
                    return 1
                if status == "__back__":
                    continue
                st.workdir = value

            l = _menu_choice(
                "Set optional runtime UAGENT_LANG?",
                ["No", "Yes"],
                default_index=1,
                allow_back=True,
            )
            if l == "__quit__":
                print("Cancelled.")
                return 1
            if l == "__back__":
                continue
            st.lang_enabled = l == "2"
            if st.lang_enabled:
                status, value = _ask_lang(st.lang, allow_back=True)
                if status == "__quit__":
                    print("Cancelled.")
                    return 1
                if status == "__back__":
                    continue
                st.lang = value

            stage = 4
            continue

        if stage == 4:
            status, out_sel = _ask_outputs(allow_back=True)
            if status == "__quit__":
                print("Cancelled.")
                return 1
            if status == "__back__":
                stage = 3
                continue
            outputs = out_sel

            stage = 5
            continue

        if stage == 5:
            print()
            print("Summary")
            print(f"  Provider: {st.provider}")
            for key, _, _ in PROVIDER_FIELDS[st.provider]:
                print(f"  {key}={(st.values or {}).get(key, '')}")
            print(f"  Responses enabled: {'yes' if st.responses_enabled else 'no'}")
            if st.responses_enabled:
                print(f"  UAGENT_REASONING={st.reasoning}")
                print(f"  UAGENT_VERBOSITY={st.verbosity}")
            print(f"  UAGENT_WORKDIR enabled: {'yes' if st.workdir_enabled else 'no'}")
            if st.workdir_enabled:
                print(f"  UAGENT_WORKDIR={st.workdir}")
            print(f"  UAGENT_LANG enabled: {'yes' if st.lang_enabled else 'no'}")
            if st.lang_enabled:
                print(f"  UAGENT_LANG={st.lang}")
            print(f"  Outputs: {', '.join(sorted(outputs))}")

            action = _menu_choice(
                "Generate files with this configuration?",
                ["Yes, generate", "Back"],
                default_index=1,
                allow_back=False,
            )
            if action == "__quit__":
                print("Cancelled.")
                return 1
            if action == "2":
                stage = 4
                continue
            break

    out_dir = Path.cwd().resolve()
    paths: dict[str, Path] = {
        "env": out_dir / ".env",
        "sh": out_dir / "env.sh",
        "ps1": out_dir / "env.ps1",
        "bat": out_dir / "env.bat",
    }

    targets = [paths[k] for k in ("env", "sh", "ps1", "bat") if k in outputs]
    existing = [p for p in targets if p.exists()]
    if existing:
        print()
        print("The following files already exist and will be overwritten:")
        for p in existing:
            print(f"  - {p}")
        yn = _menu_choice("Proceed?", ["No", "Yes"], default_index=1, allow_back=False)
        if yn == "__quit__" or yn == "1":
            print("Cancelled.")
            return 1

    env_lines = _env_lines_from_state(st)

    if "env" in outputs:
        env_text = "\n".join(env_lines).rstrip() + "\n"
        paths["env"].write_text(env_text, encoding="utf-8", newline="\n")

    if "sh" in outputs:
        sh_text = _emit_sh(env_lines)
        paths["sh"].write_text(sh_text, encoding="utf-8", newline="\n")

    if "ps1" in outputs:
        ps1_text = _emit_ps1(env_lines).replace("\n", "\r\n")
        # newline="" means: do not translate; we already have CRLF.
        paths["ps1"].write_text(ps1_text, encoding="utf-8-sig", newline="")

    if "bat" in outputs:
        bat_text = _emit_bat(env_lines)
        paths["bat"].write_text(bat_text, encoding="cp932", newline="")

    print()
    for k in ("env", "sh", "ps1", "bat"):
        if k in outputs:
            print(f"generated: {paths[k]}")

    if "ps1" in outputs:
        print("- env.ps1 : utf-8-sig, CRLF")
    if "bat" in outputs:
        print("- env.bat : cp932, CRLF")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
