#!/usr/bin/env bash
# Auto-generated by uag_setup
# Do not edit this file directly. Re-run uag_setup to regenerate.

# .env for uag (generated by `uag_setup`)
#
# Notes:
# - This file may contain secrets (API keys). Do NOT commit it to Git.
# - You can re-run `uag_setup` anytime to regenerate.

# ==============================
# Provider selection
# ==============================
# azure / openai / bedrock / openrouter / gemini / vertexai / grok / claude / ollama / nvidia
export UAGENT_PROVIDER="ollama"

# ==============================
# export OpenAI-compatible (UAGENT_PROVIDER="openai)"
# ==============================
# export UAGENT_OPENAI_API_KEY=""
# export UAGENT_OPENAI_BASE_URL=""
# export UAGENT_OPENAI_DEPNAME=""

# ==============================
# export Azure OpenAI (UAGENT_PROVIDER="azure)"
# ==============================
# export UAGENT_AZURE_BASE_URL=""
# export UAGENT_AZURE_API_KEY=""
# export UAGENT_AZURE_API_VERSION=""
# export UAGENT_AZURE_DEPNAME=""

# ==============================
# export Bedrock OpenAI-compatible gateway (UAGENT_PROVIDER="bedrock)"
# ==============================
# export UAGENT_BEDROCK_BASE_URL=""
# export UAGENT_BEDROCK_API_KEY=""
# export UAGENT_BEDROCK_DEPNAME=""

# ==============================
# export OpenRouter (UAGENT_PROVIDER="openrouter)"
# ==============================
# export UAGENT_OPENROUTER_API_KEY=""
# export UAGENT_OPENROUTER_BASE_URL=""
# export UAGENT_OPENROUTER_DEPNAME=""
# export UAGENT_OPENROUTER_FALLBACK_MODELS=""

# ==============================
# export Gemini (UAGENT_PROVIDER="gemini)"
# ==============================
# export UAGENT_GEMINI_API_KEY=""
# export UAGENT_GEMINI_DEPNAME=""

# ==============================
# export Vertex AI (UAGENT_PROVIDER="vertexai)"
# ==============================
# export UAGENT_VERTEXAI_API_KEY=""
# export UAGENT_VERTEXAI_PROJECT=""
# export UAGENT_VERTEXAI_LOCATION=""
# export UAGENT_GOOGLE_CREDENTIALS=""
# export UAGENT_GOOGLE_LOCATION=""
# export UAGENT_VERTEXAI_DEPNAME=""

# ==============================
# export Grok (UAGENT_PROVIDER="grok)"
# ==============================
# export UAGENT_GROK_API_KEY=""
# export UAGENT_GROK_BASE_URL=""
# export UAGENT_GROK_DEPNAME=""

# ==============================
# export Claude (UAGENT_PROVIDER="claude)"
# ==============================
# export UAGENT_CLAUDE_API_KEY=""
# export UAGENT_CLAUDE_DEPNAME=""

# ==============================
# export Ollama (UAGENT_PROVIDER="ollama)"
# ==============================
export UAGENT_OLLAMA_BASE_URL="http://aispace.sbc.nttdata-sbc.co.jp/v1"
export UAGENT_OLLAMA_API_KEY="dummy"
export UAGENT_OLLAMA_DEPNAME="gemma4:26b"
export UAGENT_OLLAMA_TIMEOUT_SEC=""
export UAGENT_OLLAMA_TEMPERATURE=""
export UAGENT_OLLAMA_TOP_P=""
export UAGENT_OLLAMA_TOP_K=""
export UAGENT_OLLAMA_REPEAT_PENALTY=""
export UAGENT_OLLAMA_KEEP_ALIVE=""
export UAGENT_OLLAMA_NUM_CTX=""
export UAGENT_OLLAMA_NUM_PREDICT=""

# ==============================
# export NVIDIA (UAGENT_PROVIDER="nvidia)"
# ==============================
# export UAGENT_NVIDIA_API_KEY=""
# export UAGENT_NVIDIA_BASE_URL=""
# export UAGENT_NVIDIA_DEPNAME=""

# ==============================
# 任意: Responses API（Azure/OpenAI/Bedrock）
# ==============================
# export UAGENT_RESPONSES="1"
# export UAGENT_REASONING="medium"
# export UAGENT_VERBOSITY="medium"
export UAGENT_RESPONSES="1"
export UAGENT_REASONING="medium"
export UAGENT_VERBOSITY="medium"

# ==============================
# 任意のランタイム
# ==============================
# export UAGENT_WORKDIR="."
# export UAGENT_LANG="ja"

# ==============================
# 画像・埋め込み・音声の追加設定
# ==============================
# export UAGENT_IMG_ANALYSIS_PROVIDER=""
# export UAGENT_OPENAI_IMG_ANALYSIS_BASE_URL=""
# export UAGENT_OPENAI_IMG_ANALYSIS_API_KEY=""
# export UAGENT_OPENAI_IMG_ANALYSIS_DEPNAME=""
# export UAGENT_AZURE_IMG_ANALYSIS_BASE_URL=""
# export UAGENT_AZURE_IMG_ANALYSIS_API_KEY=""
# export UAGENT_AZURE_IMG_ANALYSIS_API_VERSION=""
# export UAGENT_AZURE_IMG_ANALYSIS_DEPNAME=""
# export UAGENT_BEDROCK_IMG_ANALYSIS_BASE_URL=""
# export UAGENT_BEDROCK_IMG_ANALYSIS_API_KEY=""
# export UAGENT_BEDROCK_IMG_ANALYSIS_DEPNAME=""
# export UAGENT_OPENROUTER_IMG_ANALYSIS_BASE_URL=""
# export UAGENT_OPENROUTER_IMG_ANALYSIS_API_KEY=""
# export UAGENT_OPENROUTER_IMG_ANALYSIS_DEPNAME=""

# export UAGENT_IMG_GENERATE_PROVIDER=""
# export UAGENT_AZURE_IMG_GENERATE_BASE_URL=""
# export UAGENT_AZURE_IMG_GENERATE_API_KEY=""
# export UAGENT_AZURE_IMG_GENERATE_API_VERSION=""
# export UAGENT_AZURE_IMG_GENERATE_DEPNAME=""
# export UAGENT_OPENAI_IMG_GENERATE_BASE_URL=""
# export UAGENT_OPENAI_IMG_GENERATE_API_KEY=""
# export UAGENT_OPENAI_IMG_GENERATE_DEPNAME=""
# export UAGENT_BEDROCK_IMG_GENERATE_BASE_URL=""
# export UAGENT_BEDROCK_IMG_GENERATE_API_KEY=""
# export UAGENT_BEDROCK_IMG_GENERATE_DEPNAME=""
# export UAGENT_OPENROUTER_IMG_GENERATE_BASE_URL=""
# export UAGENT_OPENROUTER_IMG_GENERATE_API_KEY=""
# export UAGENT_OPENROUTER_IMG_GENERATE_DEPNAME=""
# export UAGENT_GEMINI_IMG_GENERATE_BASE_URL=""
# export UAGENT_GEMINI_IMG_GENERATE_API_KEY=""
# export UAGENT_GEMINI_IMG_GENERATE_DEPNAME=""
# export UAGENT_NVIDIA_IMG_GENERATE_BASE_URL=""
# export UAGENT_NVIDIA_IMG_GENERATE_API_KEY=""
# export UAGENT_NVIDIA_IMG_GENERATE_DEPNAME=""
# export UAGENT_IMG_GENERATE_DEBUG="0"
# export UAGENT_IMAGE_OPEN="1"

export UAGENT_EMBEDDING_PROVIDER="ollama"
export UAGENT_OLLAMA_EMBEDDING_BASE_URL="http://aispace.sbc.nttdata-sbc.co.jp/v1"
export UAGENT_OLLAMA_EMBEDDING_DEPNAME="embeddinggemma:latest"

# export UAGENT_AUDIO_PROVIDER=""
# export UAGENT_AZURE_SPEECH_DEPNAME=""
# export UAGENT_OPENAI_SPEECH_DEPNAME=""
# export UAGENT_AZURE_TRANSCRIBE_DEPNAME=""
# export UAGENT_OPENAI_TRANSCRIBE_DEPNAME=""
# export UAGENT_AUDIO_OPEN="1"
