from uagent.uagent_llm import _TOTAL_ROUNDS, _TOOL_LAST_ROUND, _TOOL_AUTO_UNLOAD_ROUNDS  
print('_TOTAL_ROUNDS:', _TOTAL_ROUNDS)  
print('_TOOL_LAST_ROUND:', _TOOL_LAST_ROUND)  
print('_TOOL_AUTO_UNLOAD_ROUNDS:', _TOOL_AUTO_UNLOAD_ROUNDS)  
