<#
 Auto-generated from samples/env.sample.env by samples/generate_env_samples.py
 Do not edit this file directly. Edit env.sample.env and re-generate.
#>

# Cross-provider canonical env sample for uag (.env style)
#
# This file is the source of truth for generated shell variants:
# - env.sample.sh
# - env.sample.ps1
# - env.sample.bat
#
# Generate them with:
# python samples/generate_env_samples.py

# ==============================
# Provider selection
# ==============================
# azure / openai / bedrock / openrouter / gemini / grok / claude / nvidia
$env:UAGENT_PROVIDER = 'openai'

# ==============================
# $env:OpenAI-compatible (UAGENT_PROVIDER = 'openai)'
# ==============================
$env:UAGENT_OPENAI_API_KEY = '<your-openai-api-key>'
# $env:UAGENT_OPENAI_BASE_URL = 'https://api.openai.com/v1'
# $env:UAGENT_OPENAI_DEPNAME = 'gpt-4o'

# ==============================
# $env:Azure OpenAI (UAGENT_PROVIDER = 'azure)'
# ==============================
# $env:UAGENT_AZURE_BASE_URL = 'https://<your-resource>.openai.azure.com/'
# $env:UAGENT_AZURE_API_KEY = '<your-azure-api-key>'
# $env:UAGENT_AZURE_API_VERSION = '2024-05-01-preview'
# $env:UAGENT_AZURE_DEPNAME = 'gpt-4o'

# ==============================
# $env:Bedrock OpenAI-compatible gateway (UAGENT_PROVIDER = 'bedrock)'
# ==============================
# $env:UAGENT_BEDROCK_BASE_URL = 'https://<your-bedrock-gateway>/v1'
# $env:UAGENT_BEDROCK_API_KEY = '<your-bedrock-api-key>'
# $env:UAGENT_BEDROCK_DEPNAME = 'openai.gpt-oss-120b'

# ==============================
# $env:OpenRouter (UAGENT_PROVIDER = 'openrouter)'
# ==============================
# $env:UAGENT_OPENROUTER_API_KEY = '<your-openrouter-api-key>'
# $env:UAGENT_OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1'
# $env:UAGENT_OPENROUTER_DEPNAME = 'openai/gpt-4o'
# Optional: OpenRouter fallback extension
# $env:UAGENT_OPENROUTER_DEPNAME = 'openrouter/auto'
# $env:UAGENT_OPENROUTER_FALLBACK_MODELS = 'anthropic/claude-4.5-sonnet,openai/gpt-4o,mistral/mistral-x'

# ==============================
# $env:Gemini (UAGENT_PROVIDER = 'gemini)'
# ==============================
# $env:UAGENT_GEMINI_API_KEY = '<your-gemini-api-key>'
# $env:UAGENT_GEMINI_DEPNAME = 'gemini-1.5-flash'

# ==============================
# $env:Grok (UAGENT_PROVIDER = 'grok)'
# ==============================
# $env:UAGENT_GROK_API_KEY = '<your-grok-api-key>'
# $env:UAGENT_GROK_BASE_URL = 'https://api.x.ai/v1'
# $env:UAGENT_GROK_DEPNAME = 'grok-4-1-fast-reasoning'

# ==============================
# $env:Claude (UAGENT_PROVIDER = 'claude)'
# ==============================
# $env:UAGENT_CLAUDE_API_KEY = '<your-claude-api-key>'
# $env:UAGENT_CLAUDE_DEPNAME = 'claude-sonnet-4.5'

# ==============================
# $env:NVIDIA (UAGENT_PROVIDER = 'nvidia)'
# ==============================
# $env:UAGENT_NVIDIA_API_KEY = '<your-nvidia-api-key>'
# $env:UAGENT_NVIDIA_BASE_URL = 'https://integrate.api.nvidia.com/v1'
# $env:UAGENT_NVIDIA_DEPNAME = 'nvidia/nemotron-3-nano-30b-a3b'

# ==============================
# Optional: Responses API (Azure/OpenAI/Bedrock)
# ==============================
# $env:UAGENT_RESPONSES = '1'
# $env:UAGENT_REASONING = 'medium'
# $env:UAGENT_VERBOSITY = 'medium'

# Optional runtime
# $env:UAGENT_WORKDIR = '.'
# $env:UAGENT_LANG = 'ja'
