@echo off
REM Auto-generated from samples/env.sample.env by samples/generate_env_samples.py
REM Do not edit this file directly. Edit env.sample.env and re-generate.

REM Cross-provider canonical env sample for uag (.env style)
REM
REM This file is the source of truth for generated shell variants:
REM - env.sample.sh
REM - env.sample.ps1
REM - env.sample.bat
REM
REM Generate them with:
REM python samples/generate_env_samples.py

REM ==============================
REM Provider selection
REM ==============================
REM azure / openai / bedrock / openrouter / gemini / grok / claude / nvidia
set UAGENT_PROVIDER=openai

REM ==============================
REM set OpenAI-compatible (UAGENT_PROVIDER=openai)
REM ==============================
set UAGENT_OPENAI_API_KEY=<your-openai-api-key>
REM set UAGENT_OPENAI_BASE_URL=https://api.openai.com/v1
REM set UAGENT_OPENAI_DEPNAME=gpt-4o

REM ==============================
REM set Azure OpenAI (UAGENT_PROVIDER=azure)
REM ==============================
REM set UAGENT_AZURE_BASE_URL=https://<your-resource>.openai.azure.com/
REM set UAGENT_AZURE_API_KEY=<your-azure-api-key>
REM set UAGENT_AZURE_API_VERSION=2024-05-01-preview
REM set UAGENT_AZURE_DEPNAME=gpt-4o

REM ==============================
REM set Bedrock OpenAI-compatible gateway (UAGENT_PROVIDER=bedrock)
REM ==============================
REM set UAGENT_BEDROCK_BASE_URL=https://<your-bedrock-gateway>/v1
REM set UAGENT_BEDROCK_API_KEY=<your-bedrock-api-key>
REM set UAGENT_BEDROCK_DEPNAME=openai.gpt-oss-120b

REM ==============================
REM set OpenRouter (UAGENT_PROVIDER=openrouter)
REM ==============================
REM set UAGENT_OPENROUTER_API_KEY=<your-openrouter-api-key>
REM set UAGENT_OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
REM set UAGENT_OPENROUTER_DEPNAME=openai/gpt-4o
REM Optional: OpenRouter fallback extension
REM set UAGENT_OPENROUTER_DEPNAME=openrouter/auto
REM set UAGENT_OPENROUTER_FALLBACK_MODELS=anthropic/claude-4.5-sonnet,openai/gpt-4o,mistral/mistral-x

REM ==============================
REM set Gemini (UAGENT_PROVIDER=gemini)
REM ==============================
REM set UAGENT_GEMINI_API_KEY=<your-gemini-api-key>
REM set UAGENT_GEMINI_DEPNAME=gemini-1.5-flash

REM ==============================
REM set Grok (UAGENT_PROVIDER=grok)
REM ==============================
REM set UAGENT_GROK_API_KEY=<your-grok-api-key>
REM set UAGENT_GROK_BASE_URL=https://api.x.ai/v1
REM set UAGENT_GROK_DEPNAME=grok-4-1-fast-reasoning

REM ==============================
REM set Claude (UAGENT_PROVIDER=claude)
REM ==============================
REM set UAGENT_CLAUDE_API_KEY=<your-claude-api-key>
REM set UAGENT_CLAUDE_DEPNAME=claude-sonnet-4.5

REM ==============================
REM set NVIDIA (UAGENT_PROVIDER=nvidia)
REM ==============================
REM set UAGENT_NVIDIA_API_KEY=<your-nvidia-api-key>
REM set UAGENT_NVIDIA_BASE_URL=https://integrate.api.nvidia.com/v1
REM set UAGENT_NVIDIA_DEPNAME=nvidia/nemotron-3-nano-30b-a3b

REM ==============================
REM Optional: Responses API (Azure/OpenAI/Bedrock)
REM ==============================
REM set UAGENT_RESPONSES=1
REM set UAGENT_REASONING=medium
REM set UAGENT_VERBOSITY=medium

REM Optional runtime
REM set UAGENT_WORKDIR=.
REM set UAGENT_LANG=ja
