#!/usr/bin/env bash
# Auto-generated from samples/env.sample.env by samples/generate_env_samples.py
# Do not edit this file directly. Edit env.sample.env and re-generate.

# Cross-provider canonical env sample for uag (.env style)
#
# This file is the source of truth for generated shell variants:
# - env.sample.sh
# - env.sample.ps1
# - env.sample.bat
#
# Generate them with:
# python samples/generate_env_samples.py

# ==============================
# Provider selection
# ==============================
# azure / openai / bedrock / openrouter / gemini / grok / claude / nvidia
export UAGENT_PROVIDER="openai"

# ==============================
# export OpenAI-compatible (UAGENT_PROVIDER="openai)"
# ==============================
export UAGENT_OPENAI_API_KEY="<your-openai-api-key>"
# export UAGENT_OPENAI_BASE_URL="https://api.openai.com/v1"
# export UAGENT_OPENAI_DEPNAME="gpt-4o"

# ==============================
# export Azure OpenAI (UAGENT_PROVIDER="azure)"
# ==============================
# export UAGENT_AZURE_BASE_URL="https://<your-resource>.openai.azure.com/"
# export UAGENT_AZURE_API_KEY="<your-azure-api-key>"
# export UAGENT_AZURE_API_VERSION="2024-05-01-preview"
# export UAGENT_AZURE_DEPNAME="gpt-4o"

# ==============================
# export Bedrock OpenAI-compatible gateway (UAGENT_PROVIDER="bedrock)"
# ==============================
# export UAGENT_BEDROCK_BASE_URL="https://<your-bedrock-gateway>/v1"
# export UAGENT_BEDROCK_API_KEY="<your-bedrock-api-key>"
# export UAGENT_BEDROCK_DEPNAME="openai.gpt-oss-120b"

# ==============================
# export OpenRouter (UAGENT_PROVIDER="openrouter)"
# ==============================
# export UAGENT_OPENROUTER_API_KEY="<your-openrouter-api-key>"
# export UAGENT_OPENROUTER_BASE_URL="https://openrouter.ai/api/v1"
# export UAGENT_OPENROUTER_DEPNAME="openai/gpt-4o"
# Optional: OpenRouter fallback extension
# export UAGENT_OPENROUTER_DEPNAME="openrouter/auto"
# export UAGENT_OPENROUTER_FALLBACK_MODELS="anthropic/claude-4.5-sonnet,openai/gpt-4o,mistral/mistral-x"

# ==============================
# export Gemini (UAGENT_PROVIDER="gemini)"
# ==============================
# export UAGENT_GEMINI_API_KEY="<your-gemini-api-key>"
# export UAGENT_GEMINI_DEPNAME="gemini-1.5-flash"

# ==============================
# export Grok (UAGENT_PROVIDER="grok)"
# ==============================
# export UAGENT_GROK_API_KEY="<your-grok-api-key>"
# export UAGENT_GROK_BASE_URL="https://api.x.ai/v1"
# export UAGENT_GROK_DEPNAME="grok-4-1-fast-reasoning"

# ==============================
# export Claude (UAGENT_PROVIDER="claude)"
# ==============================
# export UAGENT_CLAUDE_API_KEY="<your-claude-api-key>"
# export UAGENT_CLAUDE_DEPNAME="claude-sonnet-4.5"

# ==============================
# export NVIDIA (UAGENT_PROVIDER="nvidia)"
# ==============================
# export UAGENT_NVIDIA_API_KEY="<your-nvidia-api-key>"
# export UAGENT_NVIDIA_BASE_URL="https://integrate.api.nvidia.com/v1"
# export UAGENT_NVIDIA_DEPNAME="nvidia/nemotron-3-nano-30b-a3b"

# ==============================
# Optional: Responses API (Azure/OpenAI/Bedrock)
# ==============================
# export UAGENT_RESPONSES="1"
# export UAGENT_REASONING="medium"
# export UAGENT_VERBOSITY="medium"

# Optional runtime
# export UAGENT_WORKDIR="."
# export UAGENT_LANG="ja"
