#!/usr/bin/env python
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE_FILE = ROOT / "env.sample.env"
OUT_SH = ROOT / "env.sample.sh"
OUT_PS1 = ROOT / "env.sample.ps1"
OUT_BAT = ROOT / "env.sample.bat"

HEADER_ENV = """# Cross-provider canonical env sample for uag (.env style)
#
# This file is auto-updated by samples/generate_env_samples.py (interactive wizard).
# You can re-run the wizard anytime to regenerate shell-specific samples.
"""

HEADER_SH = """#!/usr/bin/env bash
# Auto-generated by samples/generate_env_samples.py (interactive wizard)
# Do not edit this file directly. Re-run the wizard to regenerate.
"""

HEADER_PS1 = """<#
 Auto-generated by samples/generate_env_samples.py (interactive wizard)
 Do not edit this file directly. Re-run the wizard to regenerate.
#>
"""

HEADER_BAT = """@echo off
REM Auto-generated by samples/generate_env_samples.py (interactive wizard)
REM Do not edit this file directly. Re-run the wizard to regenerate.
"""

PROVIDERS: list[tuple[str, str]] = [
    ("openai", "OpenAI-compatible"),
    ("azure", "Azure OpenAI"),
    ("bedrock", "Bedrock OpenAI-compatible gateway"),
    ("openrouter", "OpenRouter"),
    ("gemini", "Gemini"),
    ("grok", "Grok"),
    ("claude", "Claude"),
    ("ollama", "Ollama"),
    ("nvidia", "NVIDIA"),
]

PROVIDER_FIELDS: dict[str, list[tuple[str, bool, str]]] = {
    "openai": [
        ("UAGENT_OPENAI_API_KEY", True, "OpenAI API key"),
        ("UAGENT_OPENAI_BASE_URL", False, "OpenAI base URL (optional)"),
        ("UAGENT_OPENAI_DEPNAME", False, "OpenAI model/deployment name (optional)"),
    ],
    "azure": [
        (
            "UAGENT_AZURE_BASE_URL",
            True,
            "Azure base URL (e.g. https://<resource>.openai.azure.com/)",
        ),
        ("UAGENT_AZURE_API_KEY", True, "Azure API key"),
        (
            "UAGENT_AZURE_API_VERSION",
            False,
            "Azure API version (optional, e.g. 2024-05-01-preview)",
        ),
        ("UAGENT_AZURE_DEPNAME", True, "Azure deployment name"),
    ],
    "bedrock": [
        (
            "UAGENT_BEDROCK_BASE_URL",
            True,
            "Bedrock gateway base URL (e.g. https://<gateway>/v1)",
        ),
        ("UAGENT_BEDROCK_API_KEY", True, "Bedrock API key"),
        (
            "UAGENT_BEDROCK_DEPNAME",
            True,
            "Bedrock model/deployment name (e.g. openai.gpt-oss-120b)",
        ),
    ],
    "openrouter": [
        ("UAGENT_OPENROUTER_API_KEY", True, "OpenRouter API key"),
        ("UAGENT_OPENROUTER_BASE_URL", False, "OpenRouter base URL (optional)"),
        (
            "UAGENT_OPENROUTER_DEPNAME",
            False,
            "OpenRouter model/deployment name (optional)",
        ),
        (
            "UAGENT_OPENROUTER_FALLBACK_MODELS",
            False,
            "OpenRouter fallback models (optional, comma-separated)",
        ),
    ],
    "gemini": [
        ("UAGENT_GEMINI_API_KEY", True, "Gemini API key"),
        ("UAGENT_GEMINI_DEPNAME", False, "Gemini model name (optional)"),
    ],
    "grok": [
        ("UAGENT_GROK_API_KEY", True, "Grok API key"),
        ("UAGENT_GROK_BASE_URL", False, "Grok base URL (optional)"),
        ("UAGENT_GROK_DEPNAME", False, "Grok model/deployment name (optional)"),
    ],
    "claude": [
        ("UAGENT_CLAUDE_API_KEY", True, "Claude API key"),
        ("UAGENT_CLAUDE_DEPNAME", False, "Claude model/deployment name (optional)"),
    ],
    "nvidia": [
        ("UAGENT_NVIDIA_API_KEY", True, "NVIDIA API key"),
        ("UAGENT_NVIDIA_BASE_URL", False, "NVIDIA base URL (optional)"),
        ("UAGENT_NVIDIA_DEPNAME", False, "NVIDIA model/deployment name (optional)"),
    ],
    "ollama": [
        ("UAGENT_OLLAMA_BASE_URL", True, "Ollama base URL (e.g. http://localhost:11434/v1)"),
        ("UAGENT_OLLAMA_API_KEY", False, "Ollama API key (optional, default: dummy)"),
        ("UAGENT_OLLAMA_DEPNAME", False, "Ollama model/deployment name (optional)"),
        ("UAGENT_OLLAMA_TIMEOUT_SEC", False, "Ollama request timeout in seconds (default: 60)"),
        ("UAGENT_OLLAMA_TEMPERATURE", False, "Ollama temperature (default: 0.7)"),
        ("UAGENT_OLLAMA_TOP_P", False, "Ollama top_p (default: 0.9)"),
        ("UAGENT_OLLAMA_TOP_K", False, "Ollama top_k (default: 40)"),
        ("UAGENT_OLLAMA_REPEAT_PENALTY", False, "Ollama repeat_penalty (default: 1.1)"),
        ("UAGENT_OLLAMA_KEEP_ALIVE", False, "Ollama keep_alive (default: 5m)"),
        ("UAGENT_OLLAMA_NUM_CTX", False, "Ollama num_ctx (default: 8192)"),
        ("UAGENT_OLLAMA_NUM_PREDICT", False, "Ollama num_predict (default: 1024)"),
    ],
}

RESPONSES_PROVIDERS = {"openai", "azure", "bedrock", "openrouter", "ollama"}


def _split_kv(s: str) -> tuple[str, str]:
    key, value = s.split("=", 1)
    return key.strip(), value.strip()


def _q_sh(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def _q_ps1(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _emit_sh(lines: list[str]) -> str:
    out: list[str] = [HEADER_SH.rstrip("\n"), ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# export {k}={_q_sh(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"export {k}={_q_sh(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_ps1(lines: list[str]) -> str:
    out: list[str] = [HEADER_PS1.rstrip("\n"), ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"# $env:{k} = {_q_ps1(v)}")
            else:
                out.append(f"# {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"$env:{k} = {_q_ps1(v)}")
        else:
            out.append(f"# {s}")
    return "\n".join(out).rstrip() + "\n"


def _emit_bat(lines: list[str]) -> str:
    out: list[str] = [HEADER_BAT.rstrip("\n"), ""]
    for raw in lines:
        s = raw.rstrip("\n")
        if not s.strip():
            out.append("")
            continue
        t = s.lstrip()
        if t.startswith("#"):
            body = t[1:].lstrip()
            if body and "=" in body and not body.startswith("="):
                k, v = _split_kv(body)
                out.append(f"REM set {k}={v}")
            else:
                out.append(f"REM {body}".rstrip())
            continue
        if "=" in s:
            k, v = _split_kv(s)
            out.append(f"set {k}={v}")
        else:
            out.append(f"REM {s}")
    return "\r\n".join(out).rstrip() + "\r\n"


def _parse_template_defaults(lines: list[str]) -> dict[str, str]:
    defaults: dict[str, str] = {}
    pat = re.compile(r"^\s*#?\s*([A-Z][A-Z0-9_]*)=(.*)$")
    for line in lines:
        m = pat.match(line.rstrip("\n"))
        if not m:
            continue
        defaults[m.group(1)] = m.group(2).strip()
    return defaults


def _menu_choice(
    title: str, options: list[str], default_index: int = 1, allow_back: bool = False
) -> str:
    while True:
        print()
        print(title)
        for i, text in enumerate(options, 1):
            mark = " (default)" if i == default_index else ""
            print(f"  {i}. {text}{mark}")
        extra = "Enter number"
        if allow_back:
            extra += ", b=back"
        extra += ", q=quit"
        raw = input(f"{extra}: ").strip().lower()
        if raw == "q":
            return "__quit__"
        if allow_back and raw == "b":
            return "__back__"
        if not raw:
            return str(default_index)
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return raw
        print("Invalid input. Please enter a valid number.")


def _ask_text(
    label: str, default: str = "", required: bool = False, allow_back: bool = True
) -> tuple[str, str]:
    while True:
        prompt = label
        if default:
            prompt += f" [default: {default}]"
        hint = []
        if allow_back:
            hint.append("b=back")
        hint.append("q=quit")
        prompt += f" ({', '.join(hint)}): "
        raw = input(prompt).strip()
        lower = raw.lower()
        if lower == "q":
            return "__quit__", ""
        if allow_back and lower == "b":
            return "__back__", ""
        if not raw:
            if default:
                return "ok", default
            if required:
                print("This field is required. Please enter a value.")
                continue
            return "ok", ""
        return "ok", raw


def _build_env_lines(
    template_lines: list[str],
    defaults: dict[str, str],
    values: dict[str, str],
    active_keys: set[str],
    managed_keys: set[str],
) -> list[str]:
    out: list[str] = []
    emitted: set[str] = set()
    pat = re.compile(r"^(\s*)(#\s*)?([A-Z][A-Z0-9_]*)(=.*)$")

    for raw in template_lines:
        line = raw.rstrip("\n")
        m = pat.match(line)
        if not m:
            out.append(line)
            continue

        key = m.group(3)
        if key not in managed_keys:
            out.append(line)
            continue

        val = values.get(key, defaults.get(key, ""))
        if key in active_keys:
            out.append(f"{key}={val}")
        else:
            out.append(f"# {key}={val}")
        emitted.add(key)

    for key in sorted(managed_keys - emitted):
        val = values.get(key, defaults.get(key, ""))
        if key in active_keys:
            out.append(f"{key}={val}")
        else:
            out.append(f"# {key}={val}")

    header = HEADER_ENV.rstrip("\n").split("\n")
    return header + [""] + out + [""]


def main() -> int:
    if not SOURCE_FILE.exists():
        print(f"template not found: {SOURCE_FILE}")
        return 1

    template_lines = SOURCE_FILE.read_text(encoding="utf-8").splitlines(keepends=True)
    defaults = _parse_template_defaults(template_lines)

    state: dict[str, str] = {
        "provider": defaults.get("UAGENT_PROVIDER", "openai"),
        "UAGENT_REASONING": defaults.get("UAGENT_REASONING", "medium"),
        "UAGENT_VERBOSITY": defaults.get("UAGENT_VERBOSITY", "medium"),
        "UAGENT_WORKDIR": defaults.get("UAGENT_WORKDIR", "."),
        "UAGENT_LANG": defaults.get("UAGENT_LANG", "ja"),
    }
    enabled: dict[str, bool] = {
        "responses": False,
        "workdir": False,
        "lang": False,
    }

    stage = 0
    provider_fields: list[tuple[str, bool, str]] = []
    field_index = 0

    while True:
        if stage == 0:
            options = [f"{p} ({label})" for p, label in PROVIDERS]
            choice = _menu_choice(
                "Select provider", options, default_index=1, allow_back=False
            )
            if choice == "__quit__":
                print("Cancelled.")
                return 1
            state["provider"] = PROVIDERS[int(choice) - 1][0]
            provider_fields = PROVIDER_FIELDS[state["provider"]]
            field_index = 0
            stage = 1
            continue

        if stage == 1:
            if field_index >= len(provider_fields):
                stage = 2
                continue

            key, required, label = provider_fields[field_index]
            default = state.get(key, defaults.get(key, ""))
            status, value = _ask_text(
                label, default=default, required=required, allow_back=True
            )
            if status == "__quit__":
                print("Cancelled.")
                return 1
            if status == "__back__":
                if field_index == 0:
                    stage = 0
                else:
                    field_index -= 1
                continue
            state[key] = value
            field_index += 1
            continue

        if stage == 2:
            supports = state["provider"] in RESPONSES_PROVIDERS
            if supports:
                choice = _menu_choice(
                    "Enable Responses API options?",
                    ["No", "Yes"],
                    default_index=1,
                    allow_back=True,
                )
                if choice == "__quit__":
                    print("Cancelled.")
                    return 1
                if choice == "__back__":
                    stage = 1
                    field_index = len(provider_fields) - 1
                    continue
                enabled["responses"] = choice == "2"

                if enabled["responses"]:
                    r = _menu_choice(
                        "Select reasoning",
                        ["minimal", "low", "medium", "high", "auto"],
                        default_index=3,
                        allow_back=True,
                    )
                    if r == "__quit__":
                        print("Cancelled.")
                        return 1
                    if r == "__back__":
                        continue
                    state["UAGENT_REASONING"] = [
                        "minimal",
                        "low",
                        "medium",
                        "high",
                        "auto",
                    ][int(r) - 1]

                    v = _menu_choice(
                        "Select verbosity",
                        ["low", "medium", "high"],
                        default_index=2,
                        allow_back=True,
                    )
                    if v == "__quit__":
                        print("Cancelled.")
                        return 1
                    if v == "__back__":
                        continue
                    state["UAGENT_VERBOSITY"] = ["low", "medium", "high"][int(v) - 1]
            else:
                enabled["responses"] = False

            stage = 3
            continue

        if stage == 3:
            w = _menu_choice(
                "Set optional runtime UAGENT_WORKDIR?",
                ["No", "Yes"],
                default_index=1,
                allow_back=True,
            )
            if w == "__quit__":
                print("Cancelled.")
                return 1
            if w == "__back__":
                stage = 2
                continue
            enabled["workdir"] = w == "2"
            if enabled["workdir"]:
                status, value = _ask_text(
                    "UAGENT_WORKDIR",
                    default=state["UAGENT_WORKDIR"],
                    required=False,
                    allow_back=True,
                )
                if status == "__quit__":
                    print("Cancelled.")
                    return 1
                if status == "__back__":
                    continue
                state["UAGENT_WORKDIR"] = value

            lang_choice = _menu_choice(
                "Set optional runtime UAGENT_LANG?",
                ["No", "Yes"],
                default_index=1,
                allow_back=True,
            )
            if lang_choice == "__quit__":
                print("Cancelled.")
                return 1
            if lang_choice == "__back__":
                continue
            enabled["lang"] = lang_choice == "2"
            if enabled["lang"]:
                lang_opts = [
                    "en",
                    "ja",
                    "zh_CN",
                    "zh_TW",
                    "ko",
                    "th",
                    "es",
                    "fr",
                    "custom...",
                ]
                default_idx = 2 if state["UAGENT_LANG"] == "ja" else 1
                if state["UAGENT_LANG"] in lang_opts:
                    default_idx = lang_opts.index(state["UAGENT_LANG"]) + 1
                sel = _menu_choice(
                    "Select UAGENT_LANG",
                    lang_opts,
                    default_index=default_idx,
                    allow_back=True,
                )
                if sel == "__quit__":
                    print("Cancelled.")
                    return 1
                if sel == "__back__":
                    continue
                chosen = lang_opts[int(sel) - 1]
                if chosen == "custom...":
                    status, value = _ask_text(
                        "UAGENT_LANG",
                        default=state["UAGENT_LANG"],
                        required=False,
                        allow_back=True,
                    )
                    if status == "__quit__":
                        print("Cancelled.")
                        return 1
                    if status == "__back__":
                        continue
                    state["UAGENT_LANG"] = value
                else:
                    state["UAGENT_LANG"] = chosen
            stage = 4
            continue

        if stage == 4:
            print()
            print("Summary")
            print(f"  Provider: {state['provider']}")
            for key, _, _ in PROVIDER_FIELDS[state["provider"]]:
                print(f"  {key}={state.get(key, '')}")
            print(f"  Responses enabled: {'yes' if enabled['responses'] else 'no'}")
            if enabled["responses"]:
                print(f"  UAGENT_REASONING={state['UAGENT_REASONING']}")
                print(f"  UAGENT_VERBOSITY={state['UAGENT_VERBOSITY']}")
            print(f"  UAGENT_WORKDIR enabled: {'yes' if enabled['workdir'] else 'no'}")
            if enabled["workdir"]:
                print(f"  UAGENT_WORKDIR={state['UAGENT_WORKDIR']}")
            print(f"  UAGENT_LANG enabled: {'yes' if enabled['lang'] else 'no'}")
            if enabled["lang"]:
                print(f"  UAGENT_LANG={state['UAGENT_LANG']}")

            action = _menu_choice(
                "Generate files with this configuration?",
                [
                    "Yes, generate",
                    "Back to runtime options",
                    "Back to provider settings",
                ],
                default_index=1,
                allow_back=False,
            )
            if action == "__quit__":
                print("Cancelled.")
                return 1
            if action == "2":
                stage = 3
                continue
            if action == "3":
                stage = 1
                field_index = len(provider_fields) - 1
                continue

            break

    values: dict[str, str] = dict(defaults)
    values["UAGENT_PROVIDER"] = state["provider"]

    managed_keys: set[str] = {"UAGENT_PROVIDER"}
    active_keys: set[str] = {"UAGENT_PROVIDER"}

    for p, _ in PROVIDERS:
        for key, _, _ in PROVIDER_FIELDS[p]:
            managed_keys.add(key)

    for key, _, _ in PROVIDER_FIELDS[state["provider"]]:
        val = state.get(key, "")
        values[key] = val
        if val:
            active_keys.add(key)

    managed_keys.update({"UAGENT_RESPONSES", "UAGENT_REASONING", "UAGENT_VERBOSITY"})
    if enabled["responses"]:
        values["UAGENT_RESPONSES"] = "1"
        values["UAGENT_REASONING"] = state["UAGENT_REASONING"]
        values["UAGENT_VERBOSITY"] = state["UAGENT_VERBOSITY"]
        active_keys.update({"UAGENT_RESPONSES", "UAGENT_REASONING", "UAGENT_VERBOSITY"})

    managed_keys.update({"UAGENT_WORKDIR", "UAGENT_LANG"})
    if enabled["workdir"] and state["UAGENT_WORKDIR"]:
        values["UAGENT_WORKDIR"] = state["UAGENT_WORKDIR"]
        active_keys.add("UAGENT_WORKDIR")
    if enabled["lang"] and state["UAGENT_LANG"]:
        values["UAGENT_LANG"] = state["UAGENT_LANG"]
        active_keys.add("UAGENT_LANG")

    env_lines = _build_env_lines(
        template_lines, defaults, values, active_keys, managed_keys
    )
    env_text = "\n".join(env_lines).rstrip() + "\n"

    sh_text = _emit_sh(env_lines)
    ps1_text = _emit_ps1(env_lines).replace("\n", "\r\n")
    bat_text = _emit_bat(env_lines)

    SOURCE_FILE.write_text(env_text, encoding="utf-8", newline="\n")
    OUT_SH.write_text(sh_text, encoding="utf-8", newline="\n")
    OUT_PS1.write_text(ps1_text, encoding="utf-8-sig", newline="")
    OUT_BAT.write_text(bat_text, encoding="cp932", newline="")

    print()
    print(f"updated: {SOURCE_FILE}")
    print(f"generated: {OUT_SH}")
    print(f"generated: {OUT_PS1}")
    print(f"generated: {OUT_BAT}")
    print("encoding/newline:")
    print("- env.sample.sh  : utf-8, LF")
    print("- env.sample.ps1 : utf-8-sig, CRLF")
    print("- env.sample.bat : cp932, CRLF")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
